### ISSUE TITLE
Not working with next/link import statement

### ISSUE THREAD

**Issue by DaniAkash** [basselalaraaj/rollup-plugin-exclude-dependencies-from-bundle#10]
**Describe the bug**
I'm building a package that uses `next/link` module & is bundled with rollup. The resulting bundle is packaging the next/link module instead of excluding

**To Reproduce**
A package with following import statements
```jsx
import { Menu, Transition } from '@headlessui/react'
import Link from 'next/link'
```

**Expected behavior**
Build Output:
```jsx
import{Menu as n,Transition as o}from"@headlessui/react";import"@babel/runtime/helpers/typeof";import{l as r}from"../../link-3e378a35.js"
```
Headless ui gets excluded properly however, the link module got bundled into the final output

**Additional context**
Using the latest version of the exclude dependencies package - `1.1.20`

**Comment by basselalaraaj** [comment]
I tried it out with both options set to true
```
excludeDependenciesFromBundle({
      peerDependencies: true,
      dependencies: true,
    })
```

The plugin successfully identified next/link as external and didn't add the next/link code to the bundle:
```
src/main.js → bundle.js...
./foo.js false
next/link true
```

**Comment by basselalaraaj** [comment]
This issue was closed because it has been inactive for 30 days.
