### ISSUE TITLE
should not contain @rollup/plugin-node-resolve as deps?

### ISSUE THREAD

**Issue by JiangWeixian** [basselalaraaj/rollup-plugin-exclude-dependencies-from-bundle#13]
**Describe the bug**

it looks like should not contain `@rollup/plugin-node-resolve` or `@rollup/plugin-babel` as deps

**Comment by basselalaraaj** [comment]
Fixed in https://github.com/basselalaraaj/rollup-plugin-exclude-dependencies-from-bundle/commit/4d009386c83eef86f41b630bdc99c3c1a51bbd31
