### ISSUE TITLE
Doesn't work (modules.concat is not a function)

### ISSUE THREAD

**Issue by scottc-netflix** [basselalaraaj/rollup-plugin-exclude-dependencies-from-bundle#3]
This plugin crashes with the following error:
TypeError: modules.concat is not a function
node_modules/rollup-plugin-exclude-dependencies-from-bundle/dist/rollup-plugin-exclude-dependencies-from-bundle.js:19:35)

Use rollup 2.21.0 with latest verision of this plugin with this usage:
    excludeDependenciesFromBundle({
      peerDependencies: true,
      dependencies: false
    }),

It throws the error above ^

**Comment by basselalaraaj** [comment]
@scottc-netflix 
Can you try it again with the latest version?
I tested it with rollup 2.21.0 and higher, it seems to work correctly now.
