### ISSUE TITLE
dependencies were excluded but how to import them in production env?

### ISSUE THREAD

**Issue by rainmanhhh** [basselalaraaj/rollup-plugin-exclude-dependencies-from-bundle#6]
For example, react
Uncaught TypeError: Failed to resolve module specifier "react". Relative references must start with either "/", "./", or "../"

**Comment by basselalaraaj** [comment]
@rainmanhhh what are the steps to reproduce the behavior? and what is your expectation?

**Comment by rainmanhhh** [comment]
I think I misunderstood usage of this plugin...
it's only for packaging libraries, not for web app, right?

**Comment by basselalaraaj** [comment]
> I think I misunderstood usage of this plugin...
> it's only for packaging libraries, not for web app, right?

Thats was indeed the indent of this package. To avoid big bundles for packages.
